export const ACTIONS = {
    GET__TRANSACTIONS: 'GET__TRANSACTIONS',
    TRANSACTION__ERROR: 'TRANSACTION__ERROR',
    DELETE__TRANSACTION: 'DELETE_TRANSACTION',
    DELETE__ALL: 'DELETE__ALL',
    ADD__TRANSACTION: 'ADD_TRANSACTION',
    LOAD: 'LOAD',
    LOGOUT: 'LOGOUT'
}