export const ACTIONS = {
    GET__TRANSACTIONS: 'GET__TRANSACTIONS',
    TRANSACTION__ERROR: 'TRANSACTION__ERROR', 
    DELETE__TRANSACTION: 'DELETE_TRANSACTION',
    ADD__TRANSACTION: 'ADD_TRANSACTION'
}